version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rtsp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  backend:
    build: ./backend
    ports:
      - "4000:4000"        
    env_file:
      - ./backend/.env     
    depends_on:
      - postgres
    networks:
      - my_network

  worker:
    build: ./worker
    env_file:
      - ./worker/.env
    networks:
      - my_network
    

  frontend:
    build: ./frontend
    ports:
      - "8080:80"          
    depends_on:
      - backend
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
